// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserInput struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserInput) Reset()         { *m = CreateUserInput{} }
func (m *CreateUserInput) String() string { return proto.CompactTextString(m) }
func (*CreateUserInput) ProtoMessage()    {}
func (*CreateUserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *CreateUserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserInput.Unmarshal(m, b)
}
func (m *CreateUserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserInput.Marshal(b, m, deterministic)
}
func (m *CreateUserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserInput.Merge(m, src)
}
func (m *CreateUserInput) XXX_Size() int {
	return xxx_messageInfo_CreateUserInput.Size(m)
}
func (m *CreateUserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserInput proto.InternalMessageInfo

func (m *CreateUserInput) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserInput) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserOutput struct {
	Res                  bool     `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserOutput) Reset()         { *m = CreateUserOutput{} }
func (m *CreateUserOutput) String() string { return proto.CompactTextString(m) }
func (*CreateUserOutput) ProtoMessage()    {}
func (*CreateUserOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *CreateUserOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserOutput.Unmarshal(m, b)
}
func (m *CreateUserOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserOutput.Marshal(b, m, deterministic)
}
func (m *CreateUserOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserOutput.Merge(m, src)
}
func (m *CreateUserOutput) XXX_Size() int {
	return xxx_messageInfo_CreateUserOutput.Size(m)
}
func (m *CreateUserOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserOutput proto.InternalMessageInfo

func (m *CreateUserOutput) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func init() {
	proto.RegisterType((*CreateUserInput)(nil), "proto.CreateUserInput")
	proto.RegisterType((*CreateUserOutput)(nil), "proto.CreateUserOutput")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03, 0xb3, 0x84, 0x58, 0xc1, 0x94, 0x52, 0x31, 0x17, 0xbf,
	0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x68, 0x71, 0x6a, 0x91, 0x67, 0x5e, 0x41, 0x69, 0x89, 0x90,
	0x14, 0x17, 0x47, 0x69, 0x71, 0x6a, 0x51, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x9c, 0x2f, 0x24, 0xc2, 0xc5, 0x9a, 0x9a, 0x9b, 0x98, 0x99, 0x23, 0xc1, 0x04, 0x96,
	0x80, 0x70, 0x84, 0x84, 0xb8, 0x58, 0xc0, 0xaa, 0x99, 0xc1, 0x82, 0x60, 0x36, 0xc8, 0x94, 0x82,
	0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09, 0x16, 0x88, 0x29, 0x30, 0xbe, 0x92, 0x0a, 0x97,
	0x00, 0xc2, 0x52, 0xff, 0xd2, 0x12, 0x90, 0xad, 0x02, 0x5c, 0xcc, 0x45, 0xa9, 0xc5, 0x60, 0x0b,
	0x39, 0x82, 0x40, 0x4c, 0xa3, 0x60, 0x2e, 0x01, 0xdf, 0xd4, 0xe2, 0xe2, 0xd4, 0xbc, 0xf4, 0xd4,
	0xa2, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x7b, 0x2e, 0x2e, 0x84, 0x4e, 0x21, 0x31,
	0x88, 0x5f, 0xf4, 0xd0, 0x7c, 0x20, 0x25, 0x8e, 0x21, 0x0e, 0xb1, 0x44, 0x89, 0x21, 0x89, 0x0d,
	0x2c, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x43, 0x6b, 0xba, 0x10, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessengerServiceClient is the client API for MessengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessengerServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserInput, opts ...grpc.CallOption) (*CreateUserOutput, error)
}

type messengerServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessengerServiceClient(cc *grpc.ClientConn) MessengerServiceClient {
	return &messengerServiceClient{cc}
}

func (c *messengerServiceClient) CreateUser(ctx context.Context, in *CreateUserInput, opts ...grpc.CallOption) (*CreateUserOutput, error) {
	out := new(CreateUserOutput)
	err := c.cc.Invoke(ctx, "/proto.MessengerService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessengerServiceServer is the server API for MessengerService service.
type MessengerServiceServer interface {
	CreateUser(context.Context, *CreateUserInput) (*CreateUserOutput, error)
}

// UnimplementedMessengerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessengerServiceServer struct {
}

func (*UnimplementedMessengerServiceServer) CreateUser(ctx context.Context, req *CreateUserInput) (*CreateUserOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterMessengerServiceServer(s *grpc.Server, srv MessengerServiceServer) {
	s.RegisterService(&_MessengerService_serviceDesc, srv)
}

func _MessengerService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessengerService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).CreateUser(ctx, req.(*CreateUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessengerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MessengerService",
	HandlerType: (*MessengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MessengerService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
