// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/api.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pkg/proto/api.proto

It has these top-level messages:
	CreateUserInput
	CreateUserOutput
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserInput struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *CreateUserInput) Reset()                    { *m = CreateUserInput{} }
func (m *CreateUserInput) String() string            { return proto1.CompactTextString(m) }
func (*CreateUserInput) ProtoMessage()               {}
func (*CreateUserInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserInput) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserInput) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserOutput struct {
	Retmessage string `protobuf:"bytes,1,opt,name=retmessage" json:"retmessage,omitempty"`
	Res        bool   `protobuf:"varint,2,opt,name=res" json:"res,omitempty"`
}

func (m *CreateUserOutput) Reset()                    { *m = CreateUserOutput{} }
func (m *CreateUserOutput) String() string            { return proto1.CompactTextString(m) }
func (*CreateUserOutput) ProtoMessage()               {}
func (*CreateUserOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserOutput) GetRetmessage() string {
	if m != nil {
		return m.Retmessage
	}
	return ""
}

func (m *CreateUserOutput) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func init() {
	proto1.RegisterType((*CreateUserInput)(nil), "proto.CreateUserInput")
	proto1.RegisterType((*CreateUserOutput)(nil), "proto.CreateUserOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MessengerService service

type MessengerServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserInput, opts ...grpc.CallOption) (*CreateUserOutput, error)
}

type messengerServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessengerServiceClient(cc *grpc.ClientConn) MessengerServiceClient {
	return &messengerServiceClient{cc}
}

func (c *messengerServiceClient) CreateUser(ctx context.Context, in *CreateUserInput, opts ...grpc.CallOption) (*CreateUserOutput, error) {
	out := new(CreateUserOutput)
	err := grpc.Invoke(ctx, "/proto.MessengerService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MessengerService service

type MessengerServiceServer interface {
	CreateUser(context.Context, *CreateUserInput) (*CreateUserOutput, error)
}

func RegisterMessengerServiceServer(s *grpc.Server, srv MessengerServiceServer) {
	s.RegisterService(&_MessengerService_serviceDesc, srv)
}

func _MessengerService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessengerService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).CreateUser(ctx, req.(*CreateUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessengerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MessengerService",
	HandlerType: (*MessengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MessengerService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/api.proto",
}

func init() { proto1.RegisterFile("pkg/proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xc8, 0x4e, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03, 0xb3, 0x84, 0x58, 0xc1, 0x94,
	0x52, 0x38, 0x17, 0xbf, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x68, 0x71, 0x6a, 0x91, 0x67, 0x5e,
	0x41, 0x69, 0x89, 0x90, 0x14, 0x17, 0x47, 0x69, 0x71, 0x6a, 0x51, 0x5e, 0x62, 0x6e, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x2f, 0x24, 0xc2, 0xc5, 0x9a, 0x9a, 0x9b, 0x98, 0x99,
	0x23, 0xc1, 0x04, 0x96, 0x80, 0x70, 0x84, 0x84, 0xb8, 0x58, 0xc0, 0xaa, 0x99, 0xc1, 0x82, 0x60,
	0xb6, 0x92, 0x0b, 0x97, 0x00, 0xc2, 0x60, 0xff, 0xd2, 0x12, 0x90, 0xc9, 0x72, 0x5c, 0x5c, 0x45,
	0xa9, 0x25, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0xb3, 0x91, 0x44, 0x84, 0x04, 0xb8, 0x98,
	0x8b, 0x52, 0x8b, 0xc1, 0x66, 0x73, 0x04, 0x81, 0x98, 0x46, 0xc1, 0x5c, 0x02, 0xbe, 0xa9, 0xc5,
	0xc5, 0xa9, 0x79, 0xe9, 0xa9, 0x45, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xf6, 0x5c,
	0x5c, 0x08, 0x93, 0x85, 0xc4, 0x20, 0xfe, 0xd1, 0x43, 0xf3, 0x85, 0x94, 0x38, 0x86, 0x38, 0xc4,
	0x11, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x19, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xd9,
	0x0f, 0xba, 0x18, 0x01, 0x00, 0x00,
}
